name: Build Image
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build API
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      image: ${{ steps.login-ecr.outputs.registry }}/faable-api:${{ github.sha }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build, tag, and push image to Amazon ECR
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: build/faable-api:latest
